repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: check-symlinks
    -   id: detect-private-key
    -   id: sort-simple-yaml
        files: .pre-commit-config.yaml
    -   id: destroyed-symlinks
    -   id: fix-encoding-pragma
    -   id: forbid-new-submodules
