/*
 * This file is part of AdaptiveCpp, an implementation of SYCL and C++ standard
 * parallelism for CPUs and GPUs.
 *
 * Copyright The AdaptiveCpp Contributors
 *
 * AdaptiveCpp is released under the BSD 2-Clause "Simplified" License.
 * See file LICENSE in the project root for full license details.
 */

#include "builtin_config.hpp"

#define DECLARE_DPP_BUILTIN_WITH_CTRL(dpp_ctrl)                        \
  HIPSYCL_SSCP_BUILTIN                                                \
  __acpp_int32 __acpp_sscp_dpp_builtin_dpp_ctrl_##dpp_ctrl(__acpp_int32 input); \

// Needed for gmx
DECLARE_DPP_BUILTIN_WITH_CTRL(0x101)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x102)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x104)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x111)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x112)

// ROW_RR
DECLARE_DPP_BUILTIN_WITH_CTRL(0x121)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x122)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x123)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x124)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x125)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x126)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x127)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x128)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x129)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x12A)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x12B)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x12C)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x12D)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x12E)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x12F)

// WF_SL1 CDNA only
DECLARE_DPP_BUILTIN_WITH_CTRL(0x130)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x134)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x138)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x13C)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x140)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x141)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x142)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x143)

// DPP_ROW
DECLARE_DPP_BUILTIN_WITH_CTRL(0x150)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x151)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x152)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x153)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x154)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x155)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x156)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x157)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x158)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x159)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x15A)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x15B)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x15C)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x15D)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x15E)
DECLARE_DPP_BUILTIN_WITH_CTRL(0x15F)

#undef DECLARE_DPP_BUILTIN_WITH_CTRL


#define CALL_DPP_BUILTIN_WITH_CTRL(dpp_ctrl) \
  __acpp_sscp_dpp_builtin_dpp_ctrl_##dpp_ctrl(v); \


template <int dpp_ctrl_code>
int __acpp_sscp_dpp_builtin(int v){
    switch(dpp_ctrl_code){
case 0x101:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x101)
case 0x102:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x102)
case 0x104:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x104)
case 0x111:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x111)
case 0x112:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x112)
case 0x121:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x121)
case 0x122:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x122)
case 0x123:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x123)
case 0x124:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x124)
case 0x125:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x125)
case 0x126:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x126)
case 0x127:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x127)
case 0x128:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x128)
case 0x129:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x129)
case 0x12A:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x12A)
case 0x12B:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x12B)
case 0x12C:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x12C)
case 0x12D:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x12D)
case 0x12E:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x12E)
case 0x12F:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x12F)
case 0x130:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x130)
case 0x134:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x134)
case 0x138:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x138)
case 0x13C:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x13C)
case 0x140:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x140)
case 0x141:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x141)
case 0x142:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x142)
case 0x143:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x143)
case 0x150:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x150)
case 0x151:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x151)
case 0x152:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x152)
case 0x153:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x153)
case 0x154:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x154)
case 0x155:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x155)
case 0x156:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x156)
case 0x157:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x157)
case 0x158:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x158)
case 0x159:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x159)
case 0x15A:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x15A)
case 0x15B:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x15B)
case 0x15C:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x15C)
case 0x15D:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x15D)
case 0x15E:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x15E)
case 0x15F:
    return CALL_DPP_BUILTIN_WITH_CTRL(0x15F)
    }
}


#undef CALL_DPP_BUILTIN_WITH_CTRLE