/*
 * This file is part of AdaptiveCpp, an implementation of SYCL and C++ standard
 * parallelism for CPUs and GPUs.
 *
 * Copyright The AdaptiveCpp Contributors
 *
 * AdaptiveCpp is released under the BSD 2-Clause "Simplified" License.
 * See file LICENSE in the project root for full license details.
 */
// SPDX-License-Identifier: BSD-2-Clause

#include "hipSYCL/sycl/libkernel/sscp/builtins/builtin_config.hpp"
#include "hipSYCL/sycl/libkernel/sscp/builtins/amdgpu_dpp.hpp"


#define DEFINE_DPP_BUILTIN_WITH_CTRL(dpp_ctrl)                        \
  HIPSYCL_SSCP_BUILTIN                                                \
  __acpp_int32 __acpp_sscp_dpp_builtin_dpp_ctrl_##dpp_ctrl(__acpp_int32 input) {     \
    return __builtin_amdgcn_mov_dpp(input, dpp_ctrl, 0xf, 0xf, true); \
  }                                                                   \

// Needed for gmx
DEFINE_DPP_BUILTIN_WITH_CTRL(0x101)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x102)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x104)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x111)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x112)

DEFINE_DPP_BUILTIN_WITH_CTRL(0x121)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x122)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x123)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x124)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x125)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x126)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x127)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x128)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x129)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x12A)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x12B)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x12C)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x12D)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x12E)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x12F)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x130)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x134)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x138)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x13C)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x140)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x141)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x142)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x143)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x150)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x151)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x152)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x153)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x154)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x155)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x156)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x157)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x158)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x159)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x15A)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x15B)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x15C)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x15D)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x15E)
DEFINE_DPP_BUILTIN_WITH_CTRL(0x15F)
