/*
 * This file is part of hipSYCL, a SYCL implementation based on CUDA/HIP
 *
 * Copyright (c) 2022 Aksel Alpay
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef HIPSYCL_SSCP_MUSA_LIBDEVICE_INTERFACE_HPP
#define HIPSYCL_SSCP_MUSA_LIBDEVICE_INTERFACE_HPP

#include "../builtin_config.hpp"

extern "C" __hipsycl_int32 __mt_clz (__hipsycl_int32);
extern "C" __hipsycl_int32 __mt_clzll (__hipsycl_int64);
extern "C" __hipsycl_int32 __mt_popc (__hipsycl_int32);
extern "C" __hipsycl_int32 __mt_popcll (__hipsycl_int64);
extern "C" __hipsycl_int32 __mt_byte_perm (__hipsycl_int32, __hipsycl_int32, __hipsycl_int32);
extern "C" __hipsycl_int32 __mt_min (__hipsycl_int32, __hipsycl_int32);
extern "C" __hipsycl_uint32 __mt_umin (__hipsycl_uint32, __hipsycl_uint32);
extern "C" __hipsycl_int64 __mt_llmin (__hipsycl_int64, __hipsycl_int64);
extern "C" __hipsycl_uint64 __mt_ullmin (__hipsycl_uint64, __hipsycl_uint64);
extern "C" __hipsycl_int32 __mt_max (__hipsycl_int32, __hipsycl_int32);
extern "C" __hipsycl_uint32 __mt_umax (__hipsycl_uint32, __hipsycl_uint32);
extern "C" __hipsycl_int64 __mt_llmax (__hipsycl_int64, __hipsycl_int64);
extern "C" __hipsycl_uint64 __mt_ullmax (__hipsycl_uint64, __hipsycl_uint64);
extern "C" __hipsycl_int32 __mt_mulhi (__hipsycl_int32, __hipsycl_int32);
extern "C" __hipsycl_uint32 __mt_umulhi (__hipsycl_uint32, __hipsycl_uint32);
extern "C" __hipsycl_int64 __mt_mul64hi (__hipsycl_int64, __hipsycl_int64);
extern "C" __hipsycl_uint64 __mt_umul64hi (__hipsycl_uint64, __hipsycl_uint64);
extern "C" __hipsycl_int32 __mt_mul24 (__hipsycl_int32, __hipsycl_int32);
extern "C" __hipsycl_uint32 __mt_umul24 (__hipsycl_uint32, __hipsycl_uint32);
extern "C" __hipsycl_int32 __mt_brev (__hipsycl_int32);
extern "C" __hipsycl_int64 __mt_brevll (__hipsycl_int64);
extern "C" __hipsycl_int32 __mt_sad (__hipsycl_int32, __hipsycl_int32, __hipsycl_int32);
extern "C" __hipsycl_uint32 __mt_usad (__hipsycl_uint32, __hipsycl_uint32, __hipsycl_uint32);
extern "C" __hipsycl_int32 __mt_abs (__hipsycl_int32);
extern "C" __hipsycl_int64 __mt_llabs (__hipsycl_int64);
extern "C" float __mt_floorf (float);
extern "C" double __mt_floor (double);
extern "C" float __mt_fabsf (float);
extern "C" double __mt_fabs (double);
extern "C" double __mt_rcp64h (double);
extern "C" float __mt_fminf (float, float);
extern "C" float __mt_fmaxf (float, float);
extern "C" float __mt_rsqrtf (float);
extern "C" double __mt_fmin (double, double);
extern "C" double __mt_fmax (double, double);
extern "C" double __mt_rsqrt (double);
extern "C" double __mt_ceil (double);
extern "C" double __mt_trunc (double);
extern "C" float __mt_exp2f (float);
extern "C" float __mt_truncf (float);
extern "C" float __mt_ceilf (float);
extern "C" float __mt_saturatef (float);
extern "C" float __mt_fmaf_rn (float, float, float);
extern "C" float __mt_fmaf_rz (float, float, float);
extern "C" float __mt_fmaf_rd (float, float, float);
extern "C" float __mt_fmaf_ru (float, float, float);
extern "C" float __mt_fmaf_ieee_rn (float, float, float);
extern "C" float __mt_fmaf_ieee_rz (float, float, float);
extern "C" float __mt_fmaf_ieee_rd (float, float, float);
extern "C" float __mt_fmaf_ieee_ru (float, float, float);
extern "C" double __mt_fma_rn (double, double, double);
extern "C" double __mt_fma_rz (double, double, double);
extern "C" double __mt_fma_rd (double, double, double);
extern "C" double __mt_fma_ru (double, double, double);
extern "C" float __mt_fast_fdividef (float, float);
extern "C" float __mt_fdiv_rn (float, float);
extern "C" float __mt_fdiv_rz (float, float);
extern "C" float __mt_fdiv_rd (float, float);
extern "C" float __mt_fdiv_ru (float, float);
extern "C" float __mt_frcp_rn (float);
extern "C" float __mt_frcp_rz (float);
extern "C" float __mt_frcp_rd (float);
extern "C" float __mt_frcp_ru (float);
extern "C" float __mt_fsqrt_rn (float);
extern "C" float __mt_fsqrt_rz (float);
extern "C" float __mt_fsqrt_rd (float);
extern "C" float __mt_fsqrt_ru (float);
extern "C" double __mt_ddiv_rn (double, double);
extern "C" double __mt_ddiv_rz (double, double);
extern "C" double __mt_ddiv_rd (double, double);
extern "C" double __mt_ddiv_ru (double, double);
extern "C" double __mt_drcp_rn (double);
extern "C" double __mt_drcp_rz (double);
extern "C" double __mt_drcp_rd (double);
extern "C" double __mt_drcp_ru (double);
extern "C" double __mt_dsqrt_rn (double);
extern "C" double __mt_dsqrt_rz (double);
extern "C" double __mt_dsqrt_rd (double);
extern "C" double __mt_dsqrt_ru (double);
extern "C" float __mt_sqrtf (float);
extern "C" double __mt_sqrt (double);
extern "C" double __mt_dadd_rn (double, double);
extern "C" double __mt_dadd_rz (double, double);
extern "C" double __mt_dadd_rd (double, double);
extern "C" double __mt_dadd_ru (double, double);
extern "C" double __mt_dmul_rn (double, double);
extern "C" double __mt_dmul_rz (double, double);
extern "C" double __mt_dmul_rd (double, double);
extern "C" double __mt_dmul_ru (double, double);
extern "C" float __mt_fadd_rd (float, float);
extern "C" float __mt_fadd_ru (float, float);
extern "C" float __mt_fmul_rd (float, float);
extern "C" float __mt_fmul_ru (float, float);
extern "C" float __mt_fadd_rn (float, float);
extern "C" float __mt_fadd_rz (float, float);
extern "C" float __mt_fmul_rn (float, float);
extern "C" float __mt_fmul_rz (float, float);
extern "C" float __mt_double2float_rn (double);
extern "C" float __mt_double2float_rz (double);
extern "C" float __mt_double2float_rd (double);
extern "C" float __mt_double2float_ru (double);
extern "C" __hipsycl_int32 __mt_double2int_rn (double);
extern "C" __hipsycl_int32 __mt_double2int_rz (double);
extern "C" __hipsycl_int32 __mt_double2int_rd (double);
extern "C" __hipsycl_int32 __mt_double2int_ru (double);
extern "C" __hipsycl_int32 __mt_double2uint_rn (double);
extern "C" __hipsycl_int32 __mt_double2uint_rz (double);
extern "C" __hipsycl_int32 __mt_double2uint_rd (double);
extern "C" __hipsycl_int32 __mt_double2uint_ru (double);
extern "C" double __mt_int2double_rn (__hipsycl_int32);
extern "C" double __mt_uint2double_rn (__hipsycl_uint32);
extern "C" __hipsycl_int32 __mt_float2int_rn (float);
extern "C" __hipsycl_int32 __mt_float2int_rz (float);
extern "C" __hipsycl_int32 __mt_float2int_rd (float);
extern "C" __hipsycl_int32 __mt_float2int_ru (float);
extern "C" __hipsycl_uint32 __mt_float2uint_rn (float);
extern "C" __hipsycl_uint32 __mt_float2uint_rz (float);
extern "C" __hipsycl_uint32 __mt_float2uint_rd (float);
extern "C" __hipsycl_uint32 __mt_float2uint_ru (float);
extern "C" float __mt_int2float_rn (__hipsycl_int32);
extern "C" float __mt_int2float_rz (__hipsycl_int32);
extern "C" float __mt_int2float_rd (__hipsycl_int32);
extern "C" float __mt_int2float_ru (__hipsycl_int32);
extern "C" float __mt_uint2float_rn (__hipsycl_uint32);
extern "C" float __mt_uint2float_rz (__hipsycl_uint32);
extern "C" float __mt_uint2float_rd (__hipsycl_uint32);
extern "C" float __mt_uint2float_ru (__hipsycl_uint32);
extern "C" double __mt_hiloint2double (__hipsycl_int32, __hipsycl_int32);
extern "C" __hipsycl_int32 __mt_double2loint (double);
extern "C" __hipsycl_int32 __mt_double2hiint (double);
extern "C" __hipsycl_int64 __mt_float2ll_rn (float);
extern "C" __hipsycl_int64 __mt_float2ll_rz (float);
extern "C" __hipsycl_int64 __mt_float2ll_rd (float);
extern "C" __hipsycl_int64 __mt_float2ll_ru (float);
extern "C" __hipsycl_uint64 __mt_float2ull_rn (float);
extern "C" __hipsycl_uint64 __mt_float2ull_rz (float);
extern "C" __hipsycl_uint64 __mt_float2ull_rd (float);
extern "C" __hipsycl_uint64 __mt_float2ull_ru (float);
extern "C" __hipsycl_int64 __mt_double2ll_rn (double);
extern "C" __hipsycl_int64 __mt_double2ll_rz (double);
extern "C" __hipsycl_int64 __mt_double2ll_rd (double);
extern "C" __hipsycl_int64 __mt_double2ll_ru (double);
extern "C" __hipsycl_uint64 __mt_double2ull_rn (double);
extern "C" __hipsycl_uint64 __mt_double2ull_rz (double);
extern "C" __hipsycl_uint64 __mt_double2ull_rd (double);
extern "C" __hipsycl_uint64 __mt_double2ull_ru (double);
extern "C" float __mt_ll2float_rn (__hipsycl_int64);
extern "C" float __mt_ll2float_rz (__hipsycl_int64);
extern "C" float __mt_ll2float_rd (__hipsycl_int64);
extern "C" float __mt_ll2float_ru (__hipsycl_int64);
extern "C" float __mt_ull2float_rn (__hipsycl_uint64);
extern "C" float __mt_ull2float_rz (__hipsycl_uint64);
extern "C" float __mt_ull2float_rd (__hipsycl_uint64);
extern "C" float __mt_ull2float_ru (__hipsycl_uint64);
extern "C" double __mt_ll2double_rn (__hipsycl_int64);
extern "C" double __mt_ll2double_rz (__hipsycl_int64);
extern "C" double __mt_ll2double_rd (__hipsycl_int64);
extern "C" double __mt_ll2double_ru (__hipsycl_int64);
extern "C" double __mt_ull2double_rn (__hipsycl_uint64);
extern "C" double __mt_ull2double_rz (__hipsycl_uint64);
extern "C" double __mt_ull2double_rd (__hipsycl_uint64);
extern "C" double __mt_ull2double_ru (__hipsycl_uint64);
extern "C" __hipsycl_int16 __mt_float2half_rn(float);
extern "C" float __mt_half2float (__hipsycl_int16);
extern "C" float __mt_int_as_float (__hipsycl_int32);
extern "C" __hipsycl_int32 __mt_float_as_int (float);
extern "C" float __mt_uint_as_float (__hipsycl_uint32);
extern "C" __hipsycl_uint32 __mt_float_as_uint (float);
extern "C" double __mt_longlong_as_double (__hipsycl_int64);
extern "C" __hipsycl_int64 __mt_double_as_longlong (double);
extern "C" float __mt_fast_sinf (float);
extern "C" float __mt_fast_cosf (float);
extern "C" float __mt_fast_log2f (float);
extern "C" float __mt_fast_logf (float);
extern "C" float __mt_fast_expf (float);
extern "C" float __mt_fast_tanf (float);
extern "C" void __mt_fast_sincosf (float, float*, float*);
extern "C" float __mt_fast_exp10f (float);
extern "C" float __mt_fast_log10f (float);
extern "C" float __mt_fast_powf (float, float);
extern "C" __hipsycl_int32 __mt_hadd (__hipsycl_int32, __hipsycl_int32);
extern "C" __hipsycl_int32 __mt_rhadd (__hipsycl_int32, __hipsycl_int32);
extern "C" __hipsycl_uint32 __mt_uhadd (__hipsycl_uint32, __hipsycl_uint32);
extern "C" __hipsycl_uint32 __mt_urhadd (__hipsycl_uint32, __hipsycl_uint32);
extern "C" float __mt_fsub_rn (float, float);
extern "C" float __mt_fsub_rz (float, float);
extern "C" float __mt_fsub_rd (float, float);
extern "C" float __mt_fsub_ru (float, float);
extern "C" float __mt_frsqrt_rn (float);
extern "C" __hipsycl_int32 __mt_ffs (__hipsycl_int32);
extern "C" __hipsycl_int32 __mt_ffsll (__hipsycl_int64);
extern "C" float __mt_rintf (float);
extern "C" __hipsycl_int64 __mt_llrintf (float);
extern "C" float __mt_nearbyintf (float);
extern "C" __hipsycl_int32 __mt_isnanf (float);
extern "C" __hipsycl_int32 __mt_signbitf (float);
extern "C" float __mt_copysignf (float, float);
extern "C" __hipsycl_int32 __mt_finitef (float);
extern "C" __hipsycl_int32 __mt_isinff (float);
extern "C" float __mt_nextafterf (float, float);
extern "C" float __mt_nanf (__hipsycl_int8*);
extern "C" float __mt_sinf (float);
extern "C" float __mt_cosf (float);
extern "C" void __mt_sincosf (float, float*, float*);
extern "C" float __mt_sinpif (float);
extern "C" float __mt_cospif (float);
extern "C" void __mt_sincospif (float, float*, float*);
extern "C" float __mt_tanf (float);
extern "C" float __mt_log2f (float);
extern "C" float __mt_expf (float);
extern "C" float __mt_exp10f (float);
extern "C" float __mt_coshf (float);
extern "C" float __mt_sinhf (float);
extern "C" float __mt_tanhf (float);
extern "C" float __mt_atan2f (float, float);
extern "C" float __mt_atanf (float);
extern "C" float __mt_asinf (float);
extern "C" float __mt_acosf (float);
extern "C" float __mt_logf (float);
extern "C" float __mt_log10f (float);
extern "C" float __mt_log1pf (float);
extern "C" float __mt_acoshf (float);
extern "C" float __mt_asinhf (float);
extern "C" float __mt_atanhf (float);
extern "C" float __mt_expm1f (float);
extern "C" float __mt_hypotf (float, float);
extern "C" float __mt_rhypotf (float, float);
extern "C" float __mt_norm3df (float, float, float);
extern "C" float __mt_rnorm3df (float, float, float);
extern "C" float __mt_norm4df (float, float, float, float);
extern "C" float __mt_rnorm4df (float, float, float, float);
extern "C" float __mt_normf (__hipsycl_int32, float*);
extern "C" float __mt_rnormf (__hipsycl_int32, float*);
extern "C" float __mt_cbrtf (float);
extern "C" float __mt_rcbrtf (float);
extern "C" float __mt_j0f (float);
extern "C" float __mt_j1f (float);
extern "C" float __mt_y0f (float);
extern "C" float __mt_y1f (float);
extern "C" float __mt_ynf (__hipsycl_int32, float);
extern "C" float __mt_jnf (__hipsycl_int32, float);
extern "C" float __mt_cyl_bessel_i0f (float);
extern "C" float __mt_cyl_bessel_i1f (float);
extern "C" float __mt_erff (float);
extern "C" float __mt_erfinvf (float);
extern "C" float __mt_erfcf (float);
extern "C" float __mt_erfcxf (float);
extern "C" float __mt_erfcinvf (float);
extern "C" float __mt_normcdfinvf (float);
extern "C" float __mt_normcdff (float);
extern "C" float __mt_lgammaf (float);
extern "C" float __mt_ldexpf (float, __hipsycl_int32);
extern "C" float __mt_scalbnf (float, __hipsycl_int32);
extern "C" float __mt_frexpf (float, __hipsycl_int32*);
extern "C" float __mt_modff (float, float*);
extern "C" float __mt_fmodf (float, float);
extern "C" float __mt_remainderf (float, float);
extern "C" float __mt_remquof (float, float, __hipsycl_int32*);
extern "C" float __mt_fmaf (float, float, float);
extern "C" float __mt_powif (float, __hipsycl_int32);
extern "C" double __mt_powi (double, __hipsycl_int32);
extern "C" float __mt_powf (float, float);
extern "C" float __mt_tgammaf (float);
extern "C" float __mt_roundf (float);
extern "C" __hipsycl_int64 __mt_llroundf (float);
extern "C" float __mt_fdimf (float, float);
extern "C" __hipsycl_int32 __mt_ilogbf (float);
extern "C" float __mt_logbf (float);
extern "C" double __mt_rint (double);
extern "C" __hipsycl_int64 __mt_llrint (double);
extern "C" double __mt_nearbyint (double);
extern "C" __hipsycl_int32 __mt_signbitd (double);
extern "C" __hipsycl_int32 __mt_isfinited (double);
extern "C" __hipsycl_int32 __mt_isinfd (double);
extern "C" __hipsycl_int32 __mt_isnand (double);
extern "C" double __mt_copysign (double, double);
extern "C" void __mt_sincos (double, double*, double*);
extern "C" void __mt_sincospi (double, double*, double*);
extern "C" double __mt_sin (double);
extern "C" double __mt_cos (double);
extern "C" double __mt_sinpi (double);
extern "C" double __mt_cospi (double);
extern "C" double __mt_tan (double);
extern "C" double __mt_log (double);
extern "C" double __mt_log2 (double);
extern "C" double __mt_log10 (double);
extern "C" double __mt_log1p (double);
extern "C" double __mt_exp (double);
extern "C" double __mt_exp2 (double);
extern "C" double __mt_exp10 (double);
extern "C" double __mt_expm1 (double);
extern "C" double __mt_cosh (double);
extern "C" double __mt_sinh (double);
extern "C" double __mt_tanh (double);
extern "C" double __mt_atan2 (double, double);
extern "C" double __mt_atan (double);
extern "C" double __mt_asin (double);
extern "C" double __mt_acos (double);
extern "C" double __mt_acosh (double);
extern "C" double __mt_asinh (double);
extern "C" double __mt_atanh (double);
extern "C" double __mt_hypot (double, double);
extern "C" double __mt_rhypot (double, double);
extern "C" double __mt_norm3d (double, double, double);
extern "C" double __mt_rnorm3d (double, double, double);
extern "C" double __mt_norm4d (double, double, double, double);
extern "C" double __mt_rnorm4d (double, double, double, double);
extern "C" double __mt_norm (__hipsycl_int32, double*);
extern "C" double __mt_rnorm (__hipsycl_int32, double*);
extern "C" double __mt_cbrt (double);
extern "C" double __mt_rcbrt (double);
extern "C" double __mt_pow (double, double);
extern "C" double __mt_j0 (double);
extern "C" double __mt_j1 (double);
extern "C" double __mt_y0 (double);
extern "C" double __mt_y1 (double);
extern "C" double __mt_yn (__hipsycl_int32, double);
extern "C" double __mt_jn (__hipsycl_int32, double);
extern "C" double __mt_cyl_bessel_i0 (double);
extern "C" double __mt_cyl_bessel_i1 (double);
extern "C" double __mt_erf (double);
extern "C" double __mt_erfinv (double);
extern "C" double __mt_erfcinv (double);
extern "C" double __mt_normcdfinv (double);
extern "C" double __mt_erfc (double);
extern "C" double __mt_erfcx (double);
extern "C" double __mt_normcdf (double);
extern "C" double __mt_tgamma (double);
extern "C" double __mt_lgamma (double);
extern "C" double __mt_ldexp (double, __hipsycl_int32);
extern "C" double __mt_scalbn (double, __hipsycl_int32);
extern "C" double __mt_frexp (double, __hipsycl_int32*);
extern "C" double __mt_modf (double, double*);
extern "C" double __mt_fmod (double, double);
extern "C" double __mt_remainder (double, double);
extern "C" double __mt_remquo (double, double, __hipsycl_int32*);
extern "C" double __mt_nextafter (double, double);
extern "C" double __mt_nan (__hipsycl_int8*);
extern "C" double __mt_round (double);
extern "C" __hipsycl_int64 __mt_llround (double);
extern "C" double __mt_fdim (double, double);
extern "C" __hipsycl_int32 __mt_ilogb (double);
extern "C" double __mt_logb (double);
extern "C" double __mt_fma (double, double, double);
extern "C" double __mt_dsub_rn (double, double);
extern "C" double __mt_dsub_rz (double, double);
extern "C" double __mt_dsub_ru (double, double);
extern "C" double __mt_dsub_rd (double, double);

#endif
