name: Documentation

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

  pull_request:

  push:
    branches: [ "develop" ]


jobs:

  make_documentation:
    name: "Build : Documentation"

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: pip install packages
        run: pip install -U mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-git-authors-plugin

      - name: run mkdocs
        run: mkdocs build

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./site
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1




  deploy_page:

    if: github.ref == 'refs/heads/develop'

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: make_documentation
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
