name: macOS Vulkan backend

on: [push, pull_request]
env:
  clspv_commit: '3d017c6d751cdabed1a5051b20c6bf5f71e8fd32'
jobs:
  build_vulkan:
    name: Vulkan backend macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}
        restore-keys: |
          ${{ github.job }}

    - name: install dependencies
      run: |
        set +e
        brew update
        brew install llvm@19 lld@19 libomp boost ninja molten-vk lit
        set -e

    - name: Vulkan SDK
      run: |
        wget https://sdk.lunarg.com/sdk/download/1.4.341.1/mac/vulkansdk-macos-1.4.341.1.zip
        unzip vulkansdk-macos-1.4.341.1.zip
        vulkansdk-macOS-1.4.341.1.app/Contents/MacOS/vulkansdk-macOS-1.4.341.1 --root "$GITHUB_WORKSPACE/vulkan-sdk" --accept-licenses --default-answer --confirm-command install
        echo "VULKAN_SDK=${GITHUB_WORKSPACE}/vulkan-sdk/macOS" >> $GITHUB_ENV
        echo "PATH=${GITHUB_WORKSPACE}/vulkan-sdk/macOS/bin:$PATH" >> $GITHUB_ENV
        echo "DYLD_LIBRARY_PATH=${GITHUB_WORKSPACE}/vulkan-sdk/macOS/lib:${DYLD_LIBRARY_PATH}" >> $GITHUB_ENV
        echo "VK_ADD_LAYER_PATH=${GITHUB_WORKSPACE}/vulkan-sdk/macOS/share/vulkan/explicit_layer.d" >> $GITHUB_ENV
        echo "VK_ICD_FILENAMES=${GITHUB_WORKSPACE}/vulkan-sdk/macOS/share/vulkan/icd.d/MoltenVK_icd.json" >> $GITHUB_ENV
        echo "VK_DRIVER_FILES=${GITHUB_WORKSPACE}/vulkan-sdk/macOS/share/vulkan/icd.d/MoltenVK_icd.json" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=${GITHUB_WORKSPACE}/vulkan-sdk/macOS/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

    - name: cache clspv
      id: cache-clspv
      uses: actions/cache@v4
      with:
        path: ${{github.workspace}}/clspv/build/install
        key: ${{env.clspv_commit}}

    - name: checkout clspv
      if: steps.cache-clspv.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: google/clspv
        path: clspv
        ref: ${{env.clspv_commit}}

    - name: build clspv
      if: steps.cache-clspv.outputs.cache-hit != 'true'
      run: |
        cd $GITHUB_WORKSPACE/clspv
        python3 utils/fetch_sources.py
        cmake -GNinja -S $GITHUB_WORKSPACE/clspv -B $GITHUB_WORKSPACE/clspv/build -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/clspv/build/install -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        cmake --build $GITHUB_WORKSPACE/clspv/build --target install

    - name: configure
      run: |
        vulkaninfo
        echo "PATH=$GITHUB_WORKSPACE/clspv/build/install/bin:$PATH" >> $GITHUB_ENV

    - name: build
      run: |
        LLVM_PREFIX=$(brew --prefix llvm@19)
        LLD_PREFIX=$(brew --prefix lld@19)

        mkdir build && cd build
        cmake .. -GNinja \
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
        -DWITH_OPENCL_BACKEND=OFF \
        -DWITH_METAL_BACKEND=OFF \
        -DWITH_VULKAN_BACKEND=ON \
        -DACPP_COMPILER_FEATURE_PROFILE=full \
        -DACPP_LLD_PATH=${LLD_PREFIX}/bin/ld64.lld \
        -DCLANG_EXECUTABLE_PATH=${LLVM_PREFIX}/bin/clang++ \
        -DLLVM_DIR=${LLVM_PREFIX}/lib/cmake/llvm \
        -DCMAKE_OSX_SYSROOT="$(xcrun --show-sdk-path)" \
        -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/build/install
        ninja install
        echo "PATH=${GITHUB_WORKSPACE}/build/install/bin:$PATH" >> $GITHUB_ENV
        echo "DYLD_LIBRARY_PATH=${GITHUB_WORKSPACE}/build/install/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: list acpp devices
      run: |
        acpp-info

    - name: build generic SSCP tests
      run: |
        mkdir ${GITHUB_WORKSPACE}/build/tests-sscp
        cd ${GITHUB_WORKSPACE}/build/tests-sscp
        cmake -GNinja \
          -DACPP_TARGETS="generic" \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -DAdaptiveCpp_DIR=${GITHUB_WORKSPACE}/build/install/lib/cmake/AdaptiveCpp \
          ${GITHUB_WORKSPACE}/tests
        ninja

    - name: run SYCL tests
      run: |
        cd ${GITHUB_WORKSPACE}/build/tests-sscp
        ACPP_VISIBILITY_MASK="vk" ./sycl_tests

    - name: run lit SSCP tests
      run: |
        cd ${GITHUB_WORKSPACE}/build/tests-sscp

        PATH=$(brew --prefix llvm@19)/bin:$PATH \
        ACPP_VISIBILITY_MASK="vk" \
        ninja check-sscp
